[package]
name = "frontend"
version = "0.1.0"
authors = ["Douglas Anderson <hockeybuggy@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0"
serde = "1"
serde_derive = "1"
wasm-bindgen = "0.2.67"
yew = "0.17"
